// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type PriceUpdate struct {
	SymbolName string          `json:"symbolName"`
	Session    *TradingSession `json:"session"`
}

type Symbol struct {
	ID       string            `json:"id"`
	Name     string            `json:"name"`
	Sessions []*TradingSession `json:"sessions"`
}

type TradingSession struct {
	Time  time.Time `json:"time"`
	Open  int       `json:"open"`
	Close int       `json:"close"`
	High  int       `json:"high"`
	Low   int       `json:"low"`
}
